docs: Add Consul 1.10 release notes
hashicorp/consul pull request #10489
Opened 2021-06-24 17:20 UTC by blake

2021-06-24 20:49 UTC, mikemorris commented on website/content/docs/release-notes/1-10-0.mdx
> +- **Redesigned UI and Observability Enhancements:** The Consul UI has been redesigned with a new sidebar layout and dark theme. Additionally, Kubernetes users now have the ability to deploy Prometheu
```suggestion
- **Redesigned UI and Observability Enhancements:** The Consul UI has been redesigned with a new sidebar layout. Additionally, Kubernetes users now have the ability to deploy Prometheus via the Consul Helm chart which automatically integrates it with Consul’s Service Visualization UI for displaying traffic metrics between services. Lastly, Pod and Envoy metrics can now be exposed to Prometheus using Kubernetes annotations via a single aggregated endpoint.
```
```suggestion
- **Redesigned UI and Observability Enhancements:** The Consul UI has been redesigned with a new sidebar layout and dark theme. Additionally, Kubernetes users now have the ability to deploy Prometheus via the Consul Helm chart which automatically integrates it with Consul’s Service Visualization UI for displaying traffic metrics between services. Lastly, Pod and Envoy metrics can now be exposed to Prometheus using Kubernetes annotations via a single aggregated endpoint.
```
```suggestion
- **Redesigned UI and Observability Enhancements:** The Consul UI has been redesigned with a new sidebar layout. Additionally, Kubernetes users now have the ability to deploy Prometheus via the Consul Helm chart which automatically integrates it with Consul’s Service Visualization UI for displaying traffic metrics between services. Lastly, Pod and Envoy metrics can now be exposed to Prometheus using Kubernetes annotations via a single aggregated endpoint.
```

2021-06-24 20:54 UTC, mikemorris commented on website/content/docs/release-notes/1-10-0.mdx
> +For more detailed information, please refer to the [1.10.0](https://github.com/hashicorp/consul/releases/tag/v1.10.0) release page.
```suggestion
For more detailed information, please refer to the [upgrade details page](https://www.consul.io/docs/upgrading/upgrade-specific#consul-1-10-0) and the [1.10.0 changelog](https://github.com/hashicorp/consul/releases/tag/v1.10.0).
```

2021-06-24 20:55 UTC, mikemorris requested changes
Made two suggestions, removing "dark theme" language, and linking to the upgrade details page, which in turn links to the FAQ and detailed upgrade instructions for more information on the impact of licensing changes.

2021-06-29 18:38 UTC, david-yu approved these changes
LGTM

2021-06-29 23:08 UTC, merged

2021-06-29 23:12 UTC, hc-github-team-consul-core commented
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/400731.

2021-06-29 23:12 UTC, hc-github-team-consul-core commented
:cherries::white_check_mark: Cherry pick of commit 8a832635b8c6789694c81c8423332a76bbb6fadc onto `stable-website` succeeded!

2021-06-29 23:12 UTC, hc-github-team-consul-core commented
:cherries::white_check_mark: Cherry pick of commit 8a832635b8c6789694c81c8423332a76bbb6fadc onto `release/1.10.x` succeeded!