ui: Fix dropdown option duplications
hashicorp/consul pull request #10706
Opened 2021-07-27 20:38 UTC by kaxcode

**🐛 Issue**: `Source Namespace` and `Destination Namespace` drop-downs have options duplication with onChange action. Issue reported in #10686.

**🩹  Solution**: Update `onChange` action to mutate to the selected option. This is following the [usage documentation](https://github.com/cibernox/ember-power-select-with-create#usage) for `ember-power-select-with-create` package. 

**Screenshots:**
- Before
![intention_dropdown_before](https://user-images.githubusercontent.com/19161242/127223497-f222ae08-ba67-4ffe-be3d-e3190d76020f.gif)

- After
![intention_dropdown_after](https://user-images.githubusercontent.com/19161242/127222997-535c9b88-0a5a-4e58-8fdf-e2fff703cfec.gif)

Tests: ❌ 

- [ ] Backlog

- [ ] Changelog

2021-07-27 20:47 UTC, randallmorey requested changes
Awesome work!  Since you're no longer using a named action here, can you [drop the `action` helper and use `fn` instead](https://guides.emberjs.com/release/upgrading/current-edition/action-on-and-fn/)?

2021-07-27 20:50 UTC, gsusmi approved these changes
LGTM! Agree with note about using `fn`. Ty!

2021-07-27 21:01 UTC, randallmorey approved these changes

2021-07-27 21:02 UTC, randallmorey reviewed
Sorry just one last point of feedback.  `SourceNS` and `DestinationNS` are ambiguous without a `@` or `this.` in front of them.  Going forward this will be required in Ember.  Not sure if you all are worried about this yet.  If not, disregard!

2021-07-27 21:13 UTC, kaxcode commented
> Sorry just one last point of feedback. `SourceNS` and `DestinationNS` are ambiguous without a `@` or `this.` in front of them. Going forward this will be required in Ember. Not sure if you all are worried about this yet. If not, disregard!

Yes, let me update that as well.

2021-07-27 21:31 UTC, randallmorey approved these changes

2021-07-27 21:34 UTC, merged

2021-07-27 21:34 UTC, hc-github-team-consul-core commented
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/417284.

2021-07-27 21:34 UTC, hc-github-team-consul-core commented
:cherries::white_check_mark: Cherry pick of commit eb5512fb74781ea49be743e2f0f16b3f1863ef61 onto `release/1.10.x` succeeded!

2021-07-28 19:59 UTC, hc-github-team-consul-core commented
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/417943.

2021-07-28 19:59 UTC, hc-github-team-consul-core commented
:cherries::x: Cherry pick of commit eb5512fb74781ea49be743e2f0f16b3f1863ef61 onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/417943)

2021-07-28 19:59 UTC, hc-github-team-consul-core commented
:cherries::white_check_mark: Cherry pick of commit eb5512fb74781ea49be743e2f0f16b3f1863ef61 onto `release/1.9.x` succeeded!

2021-07-28 20:03 UTC, hc-github-team-consul-core commented
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/417971.

2021-07-28 20:03 UTC, hc-github-team-consul-core commented
:cherries::x: Cherry pick of commit eb5512fb74781ea49be743e2f0f16b3f1863ef61 onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/417971)

2021-07-28 20:03 UTC, hc-github-team-consul-core commented
:cherries::x: Cherry pick of commit eb5512fb74781ea49be743e2f0f16b3f1863ef61 onto `release/1.9.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/417971)

2021-07-28 20:06 UTC, hc-github-team-consul-core commented
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/417972.

2021-07-28 20:06 UTC, hc-github-team-consul-core commented
:cherries::x: Cherry pick of commit eb5512fb74781ea49be743e2f0f16b3f1863ef61 onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/417972)

2021-07-28 20:06 UTC, hc-github-team-consul-core commented
:cherries::x: Cherry pick of commit eb5512fb74781ea49be743e2f0f16b3f1863ef61 onto `release/1.9.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/417972)

2021-07-28 20:39 UTC, hc-github-team-consul-core commented
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/417988.

2021-07-28 20:39 UTC, hc-github-team-consul-core commented
:cherries::x: Cherry pick of commit eb5512fb74781ea49be743e2f0f16b3f1863ef61 onto `release/1.9.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/417988)