Port consul-enterprise #1123 to OSS
hashicorp/consul pull request #11029
Opened 2021-09-14 20:05 UTC by markan

Signed-off-by: Mark Anderson <manderson@hashicorp.com>

2021-09-14 20:07 UTC, dhiaayachi approved these changes
LGTM! 
Missing some updates to the read to use the `Query` struct

2021-09-14 20:26 UTC, dhiaayachi requested changes

2021-09-14 20:26 UTC, dhiaayachi commented on agent/consul/state/acl_schema.go
> +					writeIndex: indexAuthMethodFromACLBindingRule,
All the reads for this index need to use a Query object instead of passing a string value.

2021-09-15 02:48 UTC, dhiaayachi approved these changes

2021-09-15 13:34 UTC, merged

2021-09-15 13:35 UTC, hc-github-team-consul-core commented
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/444720.