partitions/authmethod-index work from enterprise
hashicorp/consul pull request #11056
Opened 2021-09-16 07:30 UTC by markan

Signed-off-by: Mark Anderson <manderson@hashicorp.com>

2021-09-16 14:51 UTC, rboyer approved these changes
LGTM

2021-09-16 15:01 UTC, rboyer commented on agent/consul/state/acl_schema.go
> +				},
This is missing the `indexerSingle` stuff.

2021-09-16 15:02 UTC, rboyer requested changes
The schema in OSS is missing something.

2021-09-22 19:41 UTC, dhiaayachi approved these changes
LGTM!

2021-09-22 20:13 UTC, rboyer approved these changes

2021-09-22 20:19 UTC, merged

2021-09-22 20:20 UTC, hc-github-team-consul-core commented
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/454662.