fix aws pca certs
hashicorp/consul pull request #11470
Opened 2021-11-02 03:56 UTC by FFMMM

#### Overview

These changes just build on https://github.com/hashicorp/consul/commit/9b45107c1e907a8209ad4d38af230f2fa863fd22. ( https://github.com/hashicorp/consul/pull/10411 )

#### Notes:
* testing is done thru existing units; this PR essentially "fixes" the tests too.
* this PR is blocking https://github.com/hashicorp/consul/pull/11449

```shell
$ export ENABLE_AWS_PCA_TESTS=true
$ go test -run TestAWS ./agent/connect/ca -v
...
ok      github.com/hashicorp/consul/agent/connect/ca    35.387s
```

Signed-off-by: FFMMM <FFMMM@users.noreply.github.com>

2021-11-02 20:38 UTC, dhiaayachi requested changes
Hey @FFMMM,
Thank you for working on this, I think you missed a couple of spots where `rootPEM` and `intermediatePEM` got written:

- http://github.com/hashicorp/consul/blob/b92aa2c624c64524d3c6cd25d62a7503d6799e90/agent/connect/ca/provider_aws.go#L231-L231

- http://github.com/hashicorp/consul/blob/b92aa2c624c64524d3c6cd25d62a7503d6799e90/agent/connect/ca/provider_aws.go#L544-L544
- http://github.com/hashicorp/consul/blob/b92aa2c624c64524d3c6cd25d62a7503d6799e90/agent/connect/ca/provider_aws.go#L545-L545

2021-11-02 21:02 UTC, FFMMM commented
Thanks for the call out; let's see -- 

> Hey @FFMMM, Thank you for working on this, I think you missed a couple of spots where `rootPEM` and `intermediatePEM` got written:
> 
> * https://github.com/hashicorp/consul/blob/b92aa2c624c64524d3c6cd25d62a7503d6799e90/agent/connect/ca/provider_aws.go#L231-L231

I think this gets "EnsureTrailingNewLine" from `signCSR()`, right ?
https://github.com/hashicorp/consul/blob/b92aa2c624c64524d3c6cd25d62a7503d6799e90/agent/connect/ca/provider_aws.go#L488

> * https://github.com/hashicorp/consul/blob/b92aa2c624c64524d3c6cd25d62a7503d6799e90/agent/connect/ca/provider_aws.go#L544-L544
> * https://github.com/hashicorp/consul/blob/b92aa2c624c64524d3c6cd25d62a7503d6799e90/agent/connect/ca/provider_aws.go#L545-L545

this is 100% a miss from me -- I got confused by the `ensureCA()` but the CA is already ensured in some set behaviors!

thanks for the spots!

2021-11-02 23:05 UTC, FFMMM commented
hey @dhiaayachi thanks for all the support here -- with the last push, I think we got all the places where certs are set/ created and added some new tests for the ones I missed!

Fingers crossed 🤞🏼

2021-11-02 23:15 UTC, dhiaayachi approved these changes
Thank you again @FFMMM, LGTM!!

2021-11-03 19:21 UTC, merged

2021-11-03 19:22 UTC, hc-github-team-consul-core commented
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/492688.