Transition all endpoint tests in agent_endpoint_test.go to go through ServeHTTP
hashicorp/consul pull request #11499
Opened 2021-11-04 22:39 UTC by Mathew-Estafanous

Continues issue #11396 

**Overview:**
The goal of this PR is to transition the rest of the endpoint tests in ``agent_endpoint_test.go`` to use ServeHTTP. This is going to be a large change so I’m hoping to get some progressive feedback.

2021-11-12 13:28 UTC, Mathew-Estafanous commented
@kisunji I’m ready for a code review for this PR. However there are two issues that I’d like to bring up. First is the failing ``HealthServiceByID`` test case that I mention earlier in this PR. I’m not sure how to go about fixing it.

Secondly, the handler for ``AgentHost`` does not write to the response writer and as a result I cannot transition those tests to use ServeHTTP.

2021-11-14 14:37 UTC, Mathew-Estafanous commented
I fixed the failing ``HealthServiceByID`` test case since the response’s ``CodeWithPayloadError`` was setting the ContentType to application/json when the response was suppose to be text/plain.

2021-11-16 19:51 UTC, eculver reviewed
This looks good, especially since it even uncovered a bug in the response headers! We should let @kisunji have another pass at it though since he's been in this code recently and may have some opinions.

2021-11-23 02:59 UTC, Mathew-Estafanous commented
@eculver sorry to ping you, but I’m wondering when I should expect to have this PR reviewed and merged? It’s been sometime and I haven’t received much news regarding this PR.

2021-11-23 15:07 UTC, kisunji commented
> @eculver sorry to ping you, but I’m wondering when I should expect to have this PR reviewed and merged? It’s been sometime and I haven’t received much news regarding this PR.

Hey @Mathew-Estafanous, I've been away on break but I'm back and will take a look this week!

2021-11-25 15:51 UTC, kisunji commented
This is quite the comprehensive change! Thanks a lot for this, including the bugfix and the small cleanups in the tests.

I won't get through everything this week but will continue to review next week!

2021-12-06 17:03 UTC, kisunji requested changes
Thanks for your patience @Mathew-Estafanous! Went through it and found a few minor changes but the rest looks good 👍

2021-12-06 17:03 UTC, kisunji commented on agent/agent_endpoint_test.go
> +	// TODO: AgentHost should write to response so that we can test using ServeHTTP()
Thanks for the TODO! Definitely a valuable one here.

2021-12-06 17:07 UTC, kisunji commented
Ah there seems to be some merge conflicts 😢 Try rebasing from main and preserve this line that was added in https://github.com/hashicorp/consul/pull/11610
```
require.Empty(resp.Header().Get("X-Consul-Results-Filtered-By-ACLs"))
```

2021-12-06 19:16 UTC, Mathew-Estafanous commented
Thanks for the review @kisunji! I know this was a big change to go through.

So I first rebased and did my best to solve each merge conflict. I think everything went well, however there are a few new test cases that will now need to be changed to use ServeHTTP. I’ll try to get them done in the next hour or two.

Regarding ``int(val.DebugConfig["SerfPortLAN"].(float64))``, I believe I had to do that because json.Unmarshal seems to unmarshal numbers as float64. As a result I have to typecast to float64 before converting to int.

I _think(?)_ I fixed the issue with the two test cases that do not properly handle non-200 responses. If I didn’t, could you maybe elaborate a little more on what you meant?

2021-12-06 19:29 UTC, Mathew-Estafanous commented
I think I just discovered that I have a failing test case and I think it happened when I was “fixing” the merge conflicts. 😞

2021-12-06 19:42 UTC, kisunji commented
Nice! You got what I meant 👍 

Regarding the failing tests, https://github.com/hashicorp/consul/pull/11610 actually changed some of the assertions around cache HIT or MISS so you may have to redo the rebase or compare assertions with the PR.

Feel free to tag me for any questions or help!

2021-12-06 19:54 UTC, Mathew-Estafanous commented
@kisunji 
I was looking at the main branch and noticed t hat ``require.Equal("HIT", resp.Header().Get("X-Cache”))`` is only present in the ``TestAgentConnectAuthorize_allow`` tests. However, in my branch I somehow have them in many other tests, so I assume I’m supposed to remove all the other instances and that seems to fix the failing tests.

I’m I approaching this correctly?

2021-12-06 20:07 UTC, kisunji commented on agent/agent_endpoint_test.go
> +		require.Empty(t, resp.Header().Get("X-Consul-Results-Filtered-By-ACLs"))
Try pushing a commit reverting the changes for `TestAgent_Services_ACLFilter` (I believe these tests were added from the rebase) and see if the tests pass

2021-12-06 20:10 UTC, kisunji commented on agent/agent_endpoint_test.go
> +		require.Empty(t, resp.Header().Get("X-Consul-Results-Filtered-By-ACLs"))
It looks like these following tests were added in the rebase:
```
TestAgentConnectCALeafCert
TestAgent_Members
TestAgent_Checks
TestAgent_Services
```
Could you try restoring them to `main` first?

2021-12-06 20:13 UTC, kisunji commented on agent/agent_endpoint_test.go
> +		require.Empty(t, resp.Header().Get("X-Consul-Results-Filtered-By-ACLs"))
Actually, ignore that! I think I see the issue. Will comment on the PR

2021-12-06 20:20 UTC, kisunji reviewed
Not sure what is going on with 
```
TestAgentConnectCALeafCert_good
TestAgentConnectCALeafCert_goodNotLocal
TestAgentConnectCALeafCert_secondaryDC_good
```
But maybe try reverting the changes in those tests to see if they pass 🤔

2021-12-06 20:20 UTC, kisunji commented on agent/agent_endpoint_test.go
> +		if len(val) != 1 {
The previous assertion was for len=2, not 1

Also, I'd prefer using package `require` here for readability

2021-12-06 20:20 UTC, kisunji commented on agent/agent_endpoint_test.go
> +		if len(val) != 1 {
Same issue here, we want len=2

2021-12-06 20:20 UTC, kisunji commented on agent/agent_endpoint_test.go
> +		if len(val) != 1 {
We want len=2

2021-12-06 20:26 UTC, kisunji reviewed
Let's leave out the cache assertions if they didn't exist before

2021-12-06 20:26 UTC, kisunji commented on agent/agent_endpoint_test.go
> +		require.Equal("HIT", resp.Header().Get("X-Cache"))
Let's delete this

2021-12-06 20:26 UTC, kisunji commented on agent/agent_endpoint_test.go
> +		require.Equal("HIT", resp.Header().Get("X-Cache"))
Let's delete this

2021-12-06 20:26 UTC, kisunji commented on agent/agent_endpoint_test.go
> +		require.Equal("HIT", resp.Header().Get("X-Cache"))
Let's delete this

2021-12-06 20:32 UTC, Mathew-Estafanous commented
> Let's leave out the cache assertions if they didn't exist before

Yup I’ll do that. Looks like those cache assertions are the failing points of almost all of the failing test cases.

2021-12-06 20:58 UTC, kisunji approved these changes
I think these should be the only leftover TODOs! Thanks for your patience

2021-12-06 20:58 UTC, kisunji commented on agent/agent_endpoint_test.go
> +		require.Len(t, val, 1)
```suggestion
		require.Len(t, val, 2)
```

2021-12-06 20:58 UTC, kisunji commented on agent/agent_endpoint_test.go
> +		require.Len(t, val, 1)
```suggestion
		require.Len(t, val, 2)
		require.Empty(resp.Header().Get("X-Consul-Results-Filtered-By-ACLs"))
```

2021-12-06 20:58 UTC, kisunji commented on agent/agent_endpoint_test.go
> -		require.Empty(rsp.Header().Get("X-Consul-Results-Filtered-By-ACLs"))
Should preserve these lines

2021-12-06 21:04 UTC, Mathew-Estafanous commented
@kisunji sorry I just pushed another commit 😅 I forgot to add the ``require.NotEmpty(t, resp.Header().Get("X-Consul-Results-Filtered-By-ACLs”))`` line for each root-token test.

2021-12-06 21:07 UTC, kisunji commented
> @kisunji sorry I just pushed another commit 😅 I forgot to add the `require.NotEmpty(t, resp.Header().Get("X-Consul-Results-Filtered-By-ACLs”))` line for each root-token test.

I think it should be `require.Empty` 😛

2021-12-06 21:08 UTC, Mathew-Estafanous commented
@kisunji ohh boy....I think I’m getting a little tooo excited to push changes 😅 I’ll fix that. Sooo sorry

2021-12-06 21:27 UTC, kisunji approved these changes
😆 Happens to me all the time.
Looks great! We're currently in a code freeze for a release but I'll merge your PR shortly afterwards

2021-12-07 14:44 UTC, merged

2021-12-07 14:45 UTC, hc-github-team-consul-core commented
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/519921.