added line about wildcard intentions not supported for admin partitions
hashicorp/consul pull request #11930
Opened 2022-01-03 23:35 UTC by trujillo-adam

Noted that wildcards cannot be used as admin partition values when configuring intentions and made a few small improvements.

2022-01-04 14:34 UTC, karl-cardenas-coding requested changes
@trujillo-adam while we have this PR open, can you change the code blocks to use the new components. That way it's more intuitive that this is HCL.

2022-01-10 14:28 UTC, karl-cardenas-coding approved these changes
LGTM

2022-01-10 15:53 UTC, merged

2022-01-10 15:55 UTC, hc-github-team-consul-core commented
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/543776.

2022-01-10 15:55 UTC, hc-github-team-consul-core commented
:cherries::white_check_mark: Cherry pick of commit 0ac96c7d23f9e81467334a3ee801ced34ac00944 onto `stable-website` succeeded!

2022-01-10 15:55 UTC, hc-github-team-consul-core commented
:cherries::white_check_mark: Cherry pick of commit 0ac96c7d23f9e81467334a3ee801ced34ac00944 onto `release/1.11.x` succeeded!