Make LockRetryTime configurable in api locks
hashicorp/consul pull request #12149
Opened 2022-01-21 09:30 UTC by akzi

2022-01-21 09:30 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/consul?pullRequest=12149)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/consul?pullRequest=12149)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**wangqin.fu** seems not to be a GitHub user.
You need a GitHub account to be able to sign the CLA. If you already have a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/consul?pullRequest=12149).</sub>

2022-01-21 20:00 UTC, FFMMM requested changes
hey @akzi thanks loads for opening this!

I took a first pass here and things look good.

Would you mind adding more context on this PR? Specifically, what's the problem you are trying to solve and what use cases are you encountering it in?

Also, as reviewers, we always appreciate a good PR description.

Lastly, and more importantly, what kind of testing can we add to this change?

2022-01-22 07:53 UTC, akzi commented
many clients try to lock and unlock the same locker. sometime it will sleep for 5 second to retry when 
lock failed. this take too much time.

2022-02-08 19:51 UTC, FFMMM commented
hey @akzi thanks for following up here and for your patience with our response.

Things look good overall.

What kind of testing could we add here?

2022-02-08 19:57 UTC, eculver commented
> What kind of testing could we add here?

Just to chime in with a suggestion, if you look in the [`api/lock_test.go`](https://github.com/hashicorp/consul/blob/main/api/lock_test.go#L533-L536) file, you can see similar test consideration for the `LockWaitTime` option that you can follow for this new option. It's just a suggestion; I thought it might help get you started.

2022-03-22 19:11 UTC, Amier3 commented
Hey @akzi 

Are you still interested in working on this?

2022-09-01 01:40 UTC, closed without merging