ui: aria-menu modifier
hashicorp/consul pull request #12262
Opened 2022-02-03 16:42 UTC by johncowen

New `{{aria-menu}}` modifier, slightly based on our old, and slightly crusty pre-octane [`<AriaMenu>` component](https://github.com/hashicorp/consul/blob/f020cedab29467ed630ac173a0accd3ea5747643/ui/packages/consul-ui/app/components/aria-menu/index.js), which is now deprecated and soon to be removed. The code here has not been completely re-thought, so at some point I'll probably come back and spruce it up a little more. For now its gets us as far as we need to go.

[Rendered Docs](https://consul-ui-staging-1x3l3u5ar-hashicorp.vercel.app/ui/docs/modifiers/aria-menu)

2022-02-08 17:58 UTC, randallmorey requested changes
Can you throw a link into the docs showing the reference used for keyboard navigation?

2022-02-08 19:27 UTC, johncowen commented
The keyboard interaction was wholly modelled on GitHubs menubar menus. In the top right of the black bar at the top here.

2022-02-08 19:31 UTC, johncowen commented
K added a note in the docs here.

2022-02-08 19:32 UTC, randallmorey approved these changes

2022-02-08 19:35 UTC, johncowen commented
Merged the MenuComponent one down here, I'll just wait for tests to pass here in case and then merge down, probably tomorrow now, thanks for the reviews!

2022-02-09 09:47 UTC, merged

2022-02-09 09:48 UTC, hc-github-team-consul-core commented
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/578260.