catalog: initialize the refs map to prevent a nil panic
hashicorp/consul pull request #12277
Opened 2022-02-04 23:55 UTC by dnephin

Fixes #12258

The test was able to reproduce the panic, and the second commit fixes the test. There are other ways we could fix this, but this one seemed like the most obvious. Open to other suggestions.

TODO:
* [ ] changelog

2022-02-05 00:00 UTC, dnephin commented on agent/consul/state/catalog.go
> +		Refs:       make(map[string]struct{}),
We only create this `upstreamDownstream` type in two places. The other place already properly initializes the `Refs`, so this seemed like the most direct fix.

2022-02-07 11:13 UTC, boxofrad approved these changes

2022-02-07 19:33 UTC, freddygv requested changes
Thanks for submitting this!

A limitation I see here is that by initializing the Refs map as empty, the lifecycle of the upstreamDownstream mapping then becomes tied to the (rogue?) proxy service registration. If the proxy registration that sets the ingress as a downstream is deleted, then the topology mapping is deleted even though the ingress gateway config entry still exists.

Another bit of weirdness is that the ingress gateway config code expects to be the one managing the lifecycle of these mappings for gateways. When the config entry is updated we truncate and re-add these upstream/downstream mappings where the gateway is a downstream. So adding/removing Refs when proxies are registered, where the panic happened, is incompatible with that.

We should rethink some of these assumptions here.

2022-02-07 19:57 UTC, dnephin commented
> A limitation I see here is that by initializing the Refs map as empty, the lifecycle of the upstreamDownstream mapping then becomes tied to the (rogue?) proxy service registration

I don't think I totally follow. We should not be writing code that considers a `nil` map different from an empty map. So I think this change should be safe.

Are you saying there are other bugs here that need to be addressed? Do we need to do this as part of fixing this panic, or would those be enhancements we could make separately?

2022-02-07 20:15 UTC, luckymike commented
Is there an ETA on this bugfix being released? We reported this via Enterprise Support (ticket 65689) as we encountered the same issue attempting roughly the same configuration.

2022-02-08 18:20 UTC, freddygv commented
@luckymike We expect to have a series of patch releases before the end of the month, but the timing is still under discussion

2022-02-08 19:03 UTC, dnephin commented
Got it, I think that makes sense. I'll have another read of the code to make sure I understand the implications of this. 

Do you think I need any additional tests for this change?

2022-02-09 00:14 UTC, freddygv commented
One option is to expand the test in this PR to de-register the connect-proxy registration and then query the topology of the gateway. Adding this to your test shows the issue I'm referring to:

```go
    ca := &structs.CAConfiguration{
		Provider: "consul",
	}
	err = store.CASetConfig(0, ca)
	require.NoError(t, err)

	err = store.DeleteService(3, "the-node", "the-proxy", nil)

	_, topology, err := store.ServiceTopology(nil, "dc1", "the-ingress", structs.ServiceKindIngressGateway, acl.Allow, nil)
	require.NoError(t, err)

    # Should not be 0 because the config entry still defines "the-service" as an upstream of the gateway
	require.Len(t, topology.Upstreams, 1)
```

Note that the CA config was set because the topology endpoint traverses discovery chains and compiling chains requires CA config to know the trust domain.

2022-02-09 19:54 UTC, freddygv approved these changes

2022-02-10 00:46 UTC, dnephin commented
For posterity, Freddy and I chatted about this offline. It looks like fixing the reference count is more involved, so we're going to defer that fix so that we can get this patch released ASAP.

2022-02-10 00:48 UTC, merged

2022-02-10 00:49 UTC, hc-github-team-consul-core commented
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/578850.

2022-02-10 00:49 UTC, hc-github-team-consul-core commented
:cherries::white_check_mark: Cherry pick of commit 01784470f3b3d7d3795097b2263b1ef9773ec611 onto `release/1.11.x` succeeded!

2022-02-10 00:49 UTC, hc-github-team-consul-core commented
:cherries::white_check_mark: Cherry pick of commit 01784470f3b3d7d3795097b2263b1ef9773ec611 onto `release/1.10.x` succeeded!

2022-02-10 00:49 UTC, hc-github-team-consul-core commented
:cherries::white_check_mark: Cherry pick of commit 01784470f3b3d7d3795097b2263b1ef9773ec611 onto `release/1.9.x` succeeded!

2022-02-15 00:59 UTC, msiege2 commented
@luckymike This fix was released in our patch releases on Feb 11, 2022.

2022-02-16 01:51 UTC, luckymike commented
🙏🏻