docs: add detailed instructions for setting up external root CA
hashicorp/consul pull request #12393
Opened 2022-02-18 20:48 UTC by dnephin

Branched from #11910, this PR adds detailed instructions for how to use the new feature.

2022-03-09 20:09 UTC, karl-cardenas-coding requested changes
@trujillo-adam  this looks good to me but let's tag @webdog and @danielehc to review this as they recently interacted heavily with this doc page.

2022-03-10 13:03 UTC, danielehc approved these changes
LGTM. I like the tables to show the different options and the explanation on the different necessity of each field.

2022-03-10 16:25 UTC, webdog commented on website/content/docs/connect/ca/vault.mdx
> +Specify following parameters to define an `AuthMethod` / `auth_method` object.
```suggestion
Specify the following parameters to define an `AuthMethod` / `auth_method` object.
```

2022-03-10 16:32 UTC, webdog commented on website/content/docs/connect/ca/vault.mdx
> +When WAN Federation is enabled, each secondary datacenter must use the same Vault cluster and share the same `root_pki_path` with the primary datacenter.
```suggestion
When WAN Federation is enabled, ensuing datacenters must be configured to use the same Vault cluster and share the same `root_pki_path` as the primary datacenter.
```

2022-03-10 16:35 UTC, webdog commented on website/content/docs/connect/ca/vault.mdx
> +Consul never modifies data within the root PKI path after the path has been mounted and initialized.
```suggestion
Consul does not modify data within the root PKI path after the path has been mounted and initialized.
```

2022-03-10 16:42 UTC, webdog commented on website/content/docs/connect/ca/vault.mdx
> +The intermediate is used to sign all leaf certificates.
```suggestion
The intermediate certificate is used to sign all subsequent leaf certificates.
```

2022-03-10 18:40 UTC, trujillo-adam commented on website/content/docs/connect/ca/vault.mdx
> +
Yeah, the construct you called out was what I was trying to get away from. I can see how the term "API Key" could be confusing. I would still like to keep them in the same column to reinforce the idea that the keywords perform the same function. How about "Parameter (API, Agent)"? Or just "API, Agent"? "Resource, Agent"?  I have such a love/hate relationship with md tables.

2022-03-10 19:41 UTC, kisunji commented
Just FYI @webdog & @trujillo-adam, @dnephin has recently left Hashicorp so this PR may need some additional love to bring across the finish line.

I can get to it in a week or so but lack the background knowledge for this feature set so this might need some team involvement

2022-03-10 22:32 UTC, trujillo-adam commented
I applied as much of the feedback and answered as many questions as I could. Most of @webdog 's question will need to be addressed by @kisunji when he has a chance next week. The remaining questions have to do with Nathan's original additions, which, unfortunately, we can't ask him to clarify. 

I updated the table column headers in a way that I hope addresses @webdog 's concerns.

On hold for now.

2022-03-12 16:45 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/consul?pullRequest=12393)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/consul?pullRequest=12393)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**0** out of **2** committers have signed the CLA.


- [ ] trujillo-adam
- [ ] dnephin

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/consul?pullRequest=12393).</sub>

2022-05-01 01:31 UTC, blake commented on website/content/docs/connect/ca/vault.mdx
> +
The API takes a JSON object as input. In JSON, the keys of an object are referred to as a field.

Would it make sense to break these into two separate columns with the following headings?

| Configuration parameter | API field | Description | Type | Required |
| --- | --- | --- | --- | --- |
| `Address` |  `address` | Specifies the address of the Vault server. | String | Yes |

2022-05-01 01:40 UTC, blake commented on website/content/docs/connect/ca/vault.mdx
> +If the intermediate PKI path does not exist, Consul will attempt to mount and initialize it. This requires additional privileges by the Vault token.
```suggestion
If the intermediate PKI path does not exist, Consul will attempt to mount and initialize it. This requires [additional privileges](#consul-managed-pki-paths) by the Vault token.
```

2022-05-01 01:40 UTC, blake commented on website/content/docs/connect/ca/vault.mdx
> +   `RootPKIPath`. Optionally you may also tune the path using `vault secrets tune`.
```suggestion
1. Enable the PKI secrets engine at the path (`connect_root`) that will be used as
   `RootPKIPath` in the Connect CA configuration. Optionally you may also tune the path using `vault secrets tune`.
```

2022-05-01 01:40 UTC, blake commented on website/content/docs/connect/ca/vault.mdx
> +   `RootPKIPath`. Optionally you may also tune the path using `vault secrets tune`.
Tune apparently allows customizing details of the PKI path. https://www.vaultproject.io/docs/commands/secrets/tune

2022-05-01 01:40 UTC, blake commented on website/content/docs/connect/ca/vault.mdx
> +[sign-intermediate](https://www.vaultproject.io/api-docs/secret/pki#sign-intermediate).
This enhancement assumes that the external root CA is stored in a location that is completely external to Consul or Vault, such as protected in an HSM. The specifics of signing keys from this system will vary based on the customer's environment.

2022-05-01 01:40 UTC, blake commented on website/content/docs/connect/ca/vault.mdx
> +[`set-signed`](https://www.vaultproject.io/api-docs/secret/pki#set-signed-intermediate).
```suggestion
1. Write the `bundle.pem` to the `RootPKIPath` with
[`set-signed`](https://www.vaultproject.io/api-docs/secret/pki#set-signed-intermediate).

```shell-session
vault write connect_root/intermediate/set-signed certificate=@bundle.pem
```
```

2022-08-25 01:34 UTC, closed without merging