Docs/capigw 040 route details prefix rewrite
hashicorp/consul pull request #14175
Opened 2022-08-12 03:58 UTC by trujillo-adam

### Description
This PR completes the Route configuration reference and adds some usage information for rewriting prefix paths for incoming HTTP requests.

### Links
[Original draft](https://docs.google.com/document/d/1EyjIUFwu7WcUate0YNWmO4_dFR5KiAWHLk6spVAyi7U/)

### PR Checklist

* [ ] updated test coverage
* [X] external facing docs updated
* [ ] not a security concern

2022-08-12 04:00 UTC, trujillo-adam commented
There are still several gaps on the Routes configuration reference page that I need help filling in.

2022-08-14 17:58 UTC, trujillo-adam commented on website/content/docs/api-gateway/configuration/routes.mdx
> +| `type` | Specifies the type of comparison to use for matching the path value. You can specify the following types. <ul><li>`Exact`: Returns a match only when the entire path matches the `value` fie
```suggestion
| `type` | Specifies the type of comparison to use for matching the path value. You can specify the following types. <ul><li>`Exact`: Returns a match only when the entire path matches the `value` field (default).</li><li> `PathPrefix`: Returns a match when the path matches the regex defined in the `value` field.</li></ul> | String | Required |
```
@nathancoleman - Should the `PathPrefix` type actually be `RegularExpression` like the other matching fields? I wasn't sure if this was just an error.

2022-08-14 17:59 UTC, trujillo-adam commented on website/content/docs/api-gateway/configuration/routes.mdx
> +
I assume that you would be able to define several of each type of matching rule if you needed to narrow the matches down. If so, should we explicitly say so? Or is it reasonable for our audience to make that assumption?

2022-08-15 15:01 UTC, nathancoleman requested changes
Responding to your comments, thanks for porting this over!

Is there reason to keep the GDocs version in sync with what winds up merging here, or are you intending to throw that doc away on merge?

2022-08-15 15:01 UTC, nathancoleman commented on website/content/docs/api-gateway/configuration/routes.mdx
> +| `value` | Specifies value to match on. You can specify a specific string or a regular expression. | String | Required |
```suggestion
| `value` | Specifies value to match on. You can specify a specific string for `Exact` and `PathPrefix` types or a regular expression for the `RegularExpression` type. | String | Required |
```

2022-08-15 17:20 UTC, trujillo-adam commented
> Responding to your comments, thanks for porting this over!
> 
> Is there reason to keep the GDocs version in sync with what winds up merging here, or are you intending to throw that doc away on merge?

No reason to keep the Gdoc. The purpose of the GDoc is/was to draft and collaborate more efficiently and minimize all of the back and forth in GH. We can ignore it now that 95% of the content is finalized.

2022-08-15 20:46 UTC, trujillo-adam reviewed
One suggestion for the MeshService page.

2022-08-15 20:56 UTC, trujillo-adam commented on website/content/docs/api-gateway/configuration/routes.mdx
> +
Each rule matches requests independently. As a result, a request matching any of the conditions is considered a match.  You can configure several matching rules for each type to widen or narrow matches.

2022-08-15 20:56 UTC, trujillo-adam commented on website/content/docs/api-gateway/configuration/routes.mdx
> +
```suggestion
Each rule matches requests independently. As a result, a request matching any of the conditions is considered a match.  You can configure several matching rules for each type to widen or narrow matches.
```

2022-08-15 21:13 UTC, nathancoleman requested changes
These are the last remaining things that stick out for me code-wise. Gonna take one last look at the Vercel preview before approving

2022-08-15 21:13 UTC, nathancoleman commented on website/content/docs/api-gateway/configuration/routes.mdx
> +Each rule matches requests independently. As a result, a request matching any of the conditions is considered a match.  You can configure several matching rules for each type to widen or narrow match
```suggestion
* [request method](#rules-matches-method)

Each rule matches requests independently. As a result, a request matching any of the conditions is considered a match.  You can configure several matching rules for each type to widen or narrow matches.
```

2022-08-15 21:13 UTC, nathancoleman commented on website/content/docs/api-gateway/configuration/routes.mdx
> +| `type` | Specifies the type of comparison to use for matching the path value. You can specify the following types. <ul><li>`Exact`: Returns a match only when the entire path matches the `value` fie
```suggestion
| `type` | Specifies the type of comparison to use for matching the path value. You can specify the following types. <ul><li>`Exact`: Returns a match only when the entire path matches the `value` field (default).</li><li> `PathPrefix`: Returns a match when the path has the prefix defined in the `value` field.</li><li>`RegularExpression`: Returns a match when the path matches the regex defined in the `value` field.</li></ul> | String | Required |
```

2022-08-15 21:14 UTC, nathancoleman commented on website/content/docs/api-gateway/configuration/meshservice.mdx
> +A `MeshService` is a resource in the Kubernetes cluster that represents a service in the Consul service mesh outside the Kubernetes cluster where Consul API Gateway is deployed. The service must be i
Love this change!

2022-08-15 21:21 UTC, nathancoleman commented on website/content/docs/api-gateway/configuration/routes.mdx
> +| `remove` | Configure this field to specifify an array of header names to remove from the request header. | Array of strings | Optional |
```suggestion
| `remove` | Configure this field to specify an array of header names to remove from the request header. | Array of strings | Optional |
```

2022-08-15 21:26 UTC, nathancoleman approved these changes

2022-08-15 21:39 UTC, merged