Add support for configuring Envoys route idle_timeout
hashicorp/consul pull request #14340
Opened 2022-08-25 05:11 UTC by oulman

### Description

This PR adds support for configuring the Envoy [route level idle_timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-idle-timeout) for service-routers and local_app. For our teams scenario, this will let us extend the timeout for long-running gRPC services so that Envoy doesn't terminate the connection prematurely. 

For service-routers a `IdleTimeout` parameter has been added and for local_app a proxy config `local_idle_timeout_ms` parameter was created. I followed the [RequestTimeout](https://www.consul.io/docs/connect/config-entries/service-router#requesttimeout) and [local_request_timeout_ms](https://www.consul.io/docs/connect/proxies/envoy#local_request_timeout_ms) definitions closely.

### Testing & Reproduction steps

#### Manual Testing Steps

##### service-router IdleTimeout
Created a service-router and configured the `IdleTimeout` to 60s

```
Kind = "service-router"
Name = "waitserver"
Routes = [
  {
    Destination {
      Service = ""
      RequestTimeout = "60m"
      IdleTimeout = "60s"
    }
  }
]
```

Dumped the Envoy config and verified that the `idle_timeout` configuration parameter was set

```
<snip>
        "name": "waitserver",
        "domains": [
         "*"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/"
          },
          "route": {
           "cluster": "waitserver.default.dc1.internal.ba4be18f-a3c7-7e2f-eff4-a25a8a1fce57.consul",
           "timeout": "3600s",
           "idle_timeout": "60s"
          }
         },
<snip>
```

##### local_idle_timeout_ms

Configure `local_idle_timeout_ms` on a service proxy.config

```
service {
  name = "waitserver"
  id = "waitserver"
  address = "10.5.0.20"
  port = 9222

  connect {
    sidecar_service {
      port = 10201

      proxy {
        config {
          local_request_timeout_ms = 0
          local_idle_timeout_ms = 0
        }
      }
      check {
        name = "Connect Envoy Sidecar"
        tcp = "10.5.0.20:10201"
        interval ="10s"
      }
    }
  }
}
```

Dumped the Envoy config and verified that the `idle_timeout` configuration parameter was set on the public_listener route for `local_app`

```
{
     "route_config": {
      "@type": "type.googleapis.com/envoy.config.route.v3.RouteConfiguration",
      "name": "public_listener",
      "virtual_hosts": [
       {
        "name": "public_listener",
        "domains": [
         "*"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/"
          },
          "route": {
           "cluster": "local_app",
           "timeout": "0s",
           "idle_timeout": "0s"
          }
         }
        ]
       }
      ]
     },
```

### Links
Include any links here that might be helpful for people reviewing your PR (Tickets, GH issues, API docs, external benchmarks, tools docs, etc). If there are none, feel free to delete this section.

Please be mindful not to leak any customer or confidential information. HashiCorp employees may want to use our internal URL shortener to obfuscate links.

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [ ] not a security concern

2022-08-25 21:50 UTC, oulman commented on website/content/docs/connect/proxies/envoy.mdx
> +  disable request timeouts.
Updated. Thank you!

2022-11-02 03:05 UTC, oulman commented
@blake can you remove the stale label so this doesn't get closed? 🙏 Thanks!!

2022-11-02 14:52 UTC, jkirschner-hashicorp commented
Done. I made this PR staleproof for now!

2022-11-28 14:24 UTC, oulman commented
👋  Hi. I wanted to see now that 1.14 is out if this PR could be considered? Thanks!

2022-11-28 21:23 UTC, dhiaayachi requested changes
Thank you for working on this @oulman. I have a few comments around doc changes and I believe this is missing a test around the `local_request_timeout_ms` at the xds generation level.

2022-11-28 21:23 UTC, dhiaayachi commented on website/content/docs/connect/proxies/envoy.mdx
> +
```suggestion
```

2022-11-28 21:23 UTC, dhiaayachi commented on website/content/docs/connect/proxies/envoy.mdx
> +
```suggestion
- `local_idle_timeout_ms` - In milliseconds, the idle timeout for HTTP requests
  to the local application instance. Applies to HTTP based protocols only. If not
  specified, inherits the Envoy default for route idle timeouts (15s). A value of 0 
  disables request timeouts.

```

2022-11-28 22:52 UTC, oulman commented
>  and I believe this is missing a test around the local_request_timeout_ms at the xds generation level.

Thanks, @dhiaayachi! Is that tests in additions to the changes here?

https://github.com/hashicorp/consul/pull/14340/files#diff-fb5ad005250adf2da36018fec648de9d65d05df9de42eed95310bac480e9c0b4

2022-11-29 14:47 UTC, dhiaayachi commented
> > and I believe this is missing a test around the local_request_timeout_ms at the xds generation level.
> 
> Thanks, @dhiaayachi! Is that tests in addition to the changes here?
> 
> https://github.com/hashicorp/consul/pull/14340/files#diff-fb5ad005250adf2da36018fec648de9d65d05df9de42eed95310bac480e9c0b4

The missing test would be on the rendering side, could be an addition to [this test](http://github.com/hashicorp/consul/blob/b856a17cbf518ee1f03ea6902e9f344ce5ff3df8/agent/xds/listeners_test.go#L230-L230)

2022-11-29 15:59 UTC, oulman commented
> The missing test would be on the rendering side, could be an addition to [this test](https://github.com/hashicorp/consul/blob/b856a17cbf518ee1f03ea6902e9f344ce5ff3df8/agent/xds/listeners_test.go#L230-L230)

Ah! Thank you! I have added the `local_idle_timeout_ms` to that test [in this commit](https://github.com/hashicorp/consul/pull/14340/commits/e078ad21c4ed8057f3887193be385b474f676cfa).

2022-11-29 16:00 UTC, oulman commented
> The missing test would be on the rendering side, could be an addition to [this test](https://github.com/hashicorp/consul/blob/b856a17cbf518ee1f03ea6902e9f344ce5ff3df8/agent/xds/listeners_test.go#L230-L230)

Ah! Thank you, @dhiaayach!i I have added the `local_idle_timeout_ms` to that test [in this commit](https://github.com/hashicorp/consul/pull/14340/commits/e078ad21c4ed8057f3887193be385b474f676cfa).

2022-11-29 20:00 UTC, david-yu commented
Hi @dhiaayachi I just checked with @oulman and he has confirmed that he has addressed your comments. Are additional changes needed here?

2022-11-29 20:55 UTC, dhiaayachi approved these changes
LGTM! it would be good to have @hashicorp/consul-docs review the documentation bits.

2022-11-29 22:43 UTC, merged