docs: Consul Dataplane Version Compatibility
hashicorp/consul pull request #14710
Opened 2022-09-22 15:09 UTC by pglass

### Description

This updates the version compatibility matrix to include Consul Dataplane / Envoy versions for the upcoming beta.

2022-09-22 16:47 UTC, david-yu requested changes

2022-09-22 16:47 UTC, david-yu commented on website/content/docs/connect/proxies/envoy.mdx
> +| 1.14.x              | 1.0                      | 1.23.1                 |
```suggestion
| Consul Version      | Consul Dataplane Version | Bundled Envoy Version |
| ------------------- | ------------------------ | ---------------------- |
| 1.14.x              | 1.0.x                      | 1.23.x                |
```

2022-09-22 16:47 UTC, david-yu commented on website/content/docs/connect/proxies/envoy.mdx
> +| 1.14.x              | 1.0                      | 1.23.1                 |
Changed from Bundled, since its not possible to swap out Envoy versions. Also made the .x more apparent so we don't have to continue changing this for all versions of Envoy and Dataplane.

2022-09-22 16:59 UTC, pglass commented on website/content/docs/connect/proxies/envoy.mdx
> +| 1.14.x              | 1.0                      | 1.23.1                 |
Thanks. I'm personally fine with this! 

nit: My only thought about using something like "required" or "supported" (vs packaged/bundled) was for people that decide to build their own image for Consul Dataplane thinking they can use a different version of Envoy. Using "required" indicates they shouldn't change the Envoy version. Whereas something like "packaged" or "bundled" maybe leaves it open to other versions.

2022-09-29 16:00 UTC, pglass commented on website/content/docs/connect/proxies/envoy.mdx
> +~> **Note:** Consul Dataplane is currently in beta.
I added a "beta" disclaimer here (cc @boruszak for wording review)

2022-09-29 16:07 UTC, david-yu commented on website/content/docs/connect/proxies/envoy.mdx
> +| 1.14.x              | 1.0                      | 1.23.1                 |
I see what you are saying, my thinking was the opposite that bundled would imply you can't really change or mess with the Envoy version. Right now though we will supply the container image that contains both envoy and the data plane binary so I find that building this yourself will likely not occur very often.

2022-09-29 16:07 UTC, david-yu approved these changes

2022-10-04 20:02 UTC, merged