Fix token in cookie passthrough
hashicorp/consul pull request #15023
Opened 2022-10-18 14:22 UTC by LevelbossMike

### Description
Fixes the logic that was added in https://github.com/hashicorp/consul/pull/14495 to always fetch a token based on `TokenSecretID` when that is different from what we persisted to settings before.

This makes sure we can override the `TokenSecretID` and not only set it up once.

In addition to fixing the login logic when the application boots up, I added tests and created a mechanism that we can use from now on when we want to stub out configuration on the `env`-service.

### Testing & Reproduction steps
* setup `TokenSecretID` in a cookie and see that it will call the token endpoint with the provided value when the application boots up.

### PR Checklist

* [x] updated test coverage
* [ ] external facing docs updated
* [x] not a security concern

2022-10-18 20:18 UTC, WenInCode requested changes
Minor change (typo). Env stub looks great 👍

2022-10-18 20:18 UTC, WenInCode commented on ui/packages/consul-ui/tests/acceptance/hcp-login-test.js
> +        'service:pository/token',
```suggestion
        'service:repository/token',
```

2022-10-19 06:31 UTC, LevelbossMike commented on ui/packages/consul-ui/tests/acceptance/hcp-login-test.js
> +        'service:pository/token',
Thanks for spotting this!

2022-10-19 17:59 UTC, WenInCode approved these changes

2022-10-20 06:49 UTC, merged