Fixing CLI ACL token processing unexpected precedence
hashicorp/consul pull request #15274
Opened 2022-11-07 14:57 UTC by dttung2905

### Description
Closing  #14466 

### Testing & Reproduction steps
* I used the script below ( similar to the script in the Github Issue with minor  bash syntax changes )
* I did some local testings and found out the main reason was this block of code and the way `config` class is merged and loaded twice
https://github.com/hashicorp/consul/blob/25d272a67ab560d495575defaa311fbde9d7ab81/api/api.go#L740-L755
* The value of `config.Token` in this [function](https://github.com/hashicorp/consul/blob/25d272a67ab560d495575defaa311fbde9d7ab81/api/api.go#L653) can contain either the CLI provided or the Environment Variable due to the [merge](https://github.com/hashicorp/consul/blob/25d272a67ab560d495575defaa311fbde9d7ab81/command/flags/http.go#L150) function. Similarly, the same issue happens with `config.TokenFile` value. Hence, we need to check the value of `config.Token` against `defconfig.Token` to see whether its the CLI provided or from Environment Variable

```
#!/bin/bash
set -x
get_token () {
   local env_token_file="$1" # this
   local env_token="$2" # this
   local cli_token_file="$3"
   local cli_token="$4"
   
   export CONSUL_HTTP_TOKEN_FILE="$env_token_file"
   export CONSUL_HTTP_TOKEN="$env_token"
   
   args=""
   if test -n "$cli_token_file"
   then
      args="$args -token-file=$cli_token_file"
   fi
   if test -n "$cli_token"
   then
      args="$args -token=$cli_token"
   fi

   secretID=$(consul acl token read -self $args -format json | jq -r '.SecretID')
   echo $secretID
}

check_token() {
   local expected="$1"
   local actual="$2"

   if [ "$expected" != "$actual" ]
   then
      echo "BAD - Expected: $expected, Actual: $actual"
   else
      echo "OK  - Matched!"
   fi
}

if test -z "$BOOTSTRAP_TOKEN"
then
   BOOTSTRAP_TOKEN=$(consul acl bootstrap -format json | jq -r '.SecretID')
   echo $BOOTSTRAP_TOKEN
fi
T1=$(/home/tung/go/bin/consul acl token create -token="$BOOTSTRAP_TOKEN" -service-identity=one -format=json | jq -r '.SecretID')
T1_FILE=t1.token
T2=$(consul acl token create -token="$BOOTSTRAP_TOKEN" -service-identity=two -format=json | jq -r '.SecretID')
T2_FILE=t2.token
T3=$(consul acl token create -token="$BOOTSTRAP_TOKEN" -service-identity=three -format=json | jq -r '.SecretID')
T4=$(consul acl token create -token="$BOOTSTRAP_TOKEN" -service-identity=four -format=json | jq -r '.SecretID')
echo "$T1" > $T1_FILE
echo "$T2" > $T2_FILE

cat <<-EOF
T1: $T1
T2: $T2
T3: $T3
T4: $T4

EOF
printf "token-file cli parameter has highest precedence:                "
check_token "$T2" "$(get_token $T1_FILE "$T3" $T2_FILE "$T4")"
printf "token cli parameter takes precedence over env vars:             "
check_token "$T4" "$(get_token $T1_FILE "$T3" "" "$T4")"
printf "CONSUL_HTTP_TOKEN_FILE takes precedence over CONSUL_HTTP_TOKEN: "
check_token "$T1" "$(get_token $T1_FILE "$T3" "" "")"
printf "CONSUL_HTTP_TOKEN only:                                         "
check_token "$T3" "$(get_token "" "$T3" "" "")"

```

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [ ] not a security concern

2022-11-13 14:53 UTC, dttung2905 commented
Hi @DanStough, Is there any chance you could help me to review this MR ( or pulling someone who is able to ) ? Thanks alot.

2022-11-28 23:03 UTC, DanStough requested changes
Thank you so much for the PR, @dttung2905 👏 🥳 ! 

A couple of minor things. I don't love the complexity in the if/else conditionals, but after taking a swing at refactoring it myself, it doesn't seem like there is a cleaner way to do it. I might add a comment before the `if` stating the desired order of precedence. Also, I think it would be hard to test the environment variables, but a test confirming we choose the tokenfile over the token would be nice, even if we only provide a non-existent file path and check the error.

2022-11-29 14:48 UTC, dttung2905 commented
Thanks @DanStough for the review! . I do agree that it's not the cleanest way to do this :smiling_face_with_tear: Let me go through your comment and add extra test case like you suggested

2022-12-01 22:42 UTC, DanStough commented on api/api.go
> +		goto FINISH
I was thinking of something like this [playground example](https://go.dev/play/p/ic8zKpwSqa1). Let me know what you think.

2022-12-01 22:49 UTC, DanStough reviewed
Love the fixes! Waiting to approve until we resolve the last open comment.

2022-12-01 22:49 UTC, DanStough commented on api/api.go
> +	// 4. CONSUL_HTTP_TOKEN environment variable
Looks great 👌

2022-12-02 10:27 UTC, dttung2905 commented on api/api.go
> +		goto FINISH
Aha!. Thanks alot for the suggestion! I did not think it was that simple :100:

2022-12-02 17:09 UTC, DanStough approved these changes
LGTM 🚀

2022-12-02 17:19 UTC, merged