[docs] Don't mark client as server in agent docs
hashicorp/consul pull request #19328
Opened 2023-10-21 08:56 UTC by Sanskar531

### Description

In agent docs, it shows that a client is configured as server. Please check https://developer.hashicorp.com/consul/docs/agent#client-node-with-multiple-interfaces-or-ip-addresses 

### Testing & Reproduction steps

Visit https://developer.hashicorp.com/consul/docs/agent#client-node-with-multiple-interfaces-or-ip-addresses  and see that client is configured like this:

```hcl
server = true
``` 

```json
"server": true
```

### Links

Linked issue #18523

### PR Checklist

* [ ] updated test coverage (not applicable)
* [x] external facing docs updated
* [ ] appropriate backport labels added (not applicable)
* [ ] not a security concern (not applicable)

2023-12-24 12:09 UTC, Sanskar531 commented
Hi all! I would be nice to get someone to review this : )

2024-01-02 20:42 UTC, blake requested changes
Thanks for picking this up. I requested a small change to the node name in the agent config. Otherwise, LGTM.

2024-01-02 20:42 UTC, blake commented on website/content/docs/agent/index.mdx
>  node_name = "consul-server"
```suggestion
node_name = "consul-client"
```

2024-01-02 20:42 UTC, blake commented on website/content/docs/agent/index.mdx
>    "node_name": "consul-server",
```suggestion
  "node_name": "consul-client",
```

2024-05-28 01:30 UTC, closed without merging