Make tracing parameter configurable on ingress GW
hashicorp/consul pull request #8714
Opened 2020-09-19 17:32 UTC by Gufran

Closes: #8519 

This changeset allows tracing configuration to be specified as part of ingress-gateway connect config.

2020-09-19 17:34 UTC, Gufran commented
@blake would you be able to take a look at this and tell me if my approach is acceptable? More tests and documentation coming up.

2020-09-19 17:36 UTC, Gufran commented
I am not able to run tests locally because of some lint issues in other parts of the codebase, do I need to do anything special to ignore those issues or should `make test` have worked without any error?

2020-11-07 14:22 UTC, Gufran commented
@blake any update here? Do you think someone can review it anytime soon?

2021-02-11 16:13 UTC, freddygv requested changes
Hi @Gufran, thanks for the PR. I think this mostly looks good.

Would you be able to add tests for these new flags here?
`/command/config/write/config_write_test.go`
`/api/config_entry_test.go`

It also requires docs changes in:
`/website/content/docs/connect/config-entries/ingress-gateway.mdx`

2021-02-12 05:52 UTC, Gufran commented
@freddygv thanks for the review. I’ll add the tests and docs soon.

2021-02-12 12:43 UTC, Gufran commented
@freddygv ready for review.

2021-02-23 23:45 UTC, freddygv requested changes
Thanks for adding those tests and docs @Gufran.

I added some suggestions to the docs, since I think they might not be clear without also looking at the Envoy docs. Let me know if my interpretation seems correct.

The last remaining portion for this PR is integration testing. 

A simple case could set `random_sampling` as the strategy and 100% as the tracing percentage. Then send a request to the gateway without a `x-client-trace-id` and verify it was traced.

Another case could set `client_sampling` as the strategy and 0% as the percentage. Then send a request to the gateway with a `x-client-trace-id` and verify it wasn't traced.

Here's an example of an existing integration test for ingress gateways:
https://github.com/hashicorp/consul/blob/master/test/integration/connect/envoy/case-ingress-gateway-simple

Here is assertion in another integration test that could be useful since it inspects trace headers:
https://github.com/hashicorp/consul/blob/master/test/integration/connect/envoy/case-zipkin/verify.bats#L36

Let me know if you would like more guidance here.

2021-02-23 23:45 UTC, freddygv commented on website/content/docs/connect/config-entries/ingress-gateway.mdx
> +        '`random_sampling` strategy, this value is applicable when `x-client-trace-id` header is not set.'
I think that the description could be a bit clearer. What do you think of this?

```suggestion
        'Target percentage of requests received by the gateway that should be traced. ' + 
        'When `TracingStrategy` is set to `client_sampling` this percentage applies to requests containing the `x-client-trace-id` header. ' +
        'With the `random_sampling` tracing strategy this percentage applies to requests that do not contain the `x-client-trace-id` header.'
```

2021-02-24 13:03 UTC, Gufran commented
@freddygv  thanks for the review. Can you take a look at the integration tests please? For some reason the envoy process for ingress gateway is not starting the listener, I am not able to figure out why is that.

I went through all the logs that are captured by the test harness but can't spot any problem. The services are being registered properly, and so is ingress gateway config, all envoy processes respond on the admin endpoint but the gateway listener doesn't come up. When I query the `/listeners` admin endpoint I get back an empty response, and the `/config_dump` also shows empty listeners list.

I also tried splitting the tests into one case per permutation, but it still behaved in the same way.

Here is the test output. The last bits are for debugging and I'll remove those after fixing the problem:

<details>
<summary>Test output</summary>

```
=== RUN   TestEnvoy/case-ingress-gateway-custom-tracing
Setting up the primary datacenter
Registered service: ingress-gateway-client-sampling-0
Registered service: ingress-gateway-client-sampling-100
Registered service: ingress-gateway-random-sampling-0
Registered service: ingress-gateway-random-sampling-100
Registered service: s1
Registered service: s2
Starting services
c2c53bf2a05d1c78633fcca4a4bc4407231639771dcea4b5459a558a1b507eea
Killing and removing: envoy_verify-primary_1...done
Running primary verification step for case-ingress-gateway-custom-tracing...
1..10
ok 1 proxy admin endpoint is up on :20000
ok 2 proxy admin endpoint is up on :20001
ok 3 proxy admin endpoint is up on :20002
ok 4 proxy admin endpoint is up on :20003
ok 5 proxy admin endpoint is up on :19000
not ok 6 random sampling with 100% should send traces to zipkin/jaeger
# (in test file /workdir/primary/bats/verify.bats, line 30)
#   `[ "$status" == "0" ]' failed with status 7
# OUTPUT
not ok 7 client sampling with 0% should send traces to zipkin/jaeger
# (in test file /workdir/primary/bats/verify.bats, line 42)
#   `[ "$status" == "0" ]' failed with status 7
# OUTPUT
not ok 8 random sampling with 0% should not send traces to zipkin/jaeger
# (in test file /workdir/primary/bats/verify.bats, line 54)
#   `[ "$status" == "0" ]' failed with status 7
# OUTPUT
not ok 9 client sampling with 100% should not send traces to zipkin/jaeger
# (in test file /workdir/primary/bats/verify.bats, line 66)
#   `[ "$status" == "0" ]' failed with status 7
# OUTPUT
not ok 10 verify gateway listeners
# (in test file /workdir/primary/bats/verify.bats, line 87)
#   `[ "0" == "1" ]' failed with status 7
# LISTENER 9990: * Rebuilt URL to: localhost:9990/
# *   Trying 127.0.0.1...
# * TCP_NODELAY set
# * connect to 127.0.0.1 port 9990 failed: Connection refused
# *   Trying ::1...
# * TCP_NODELAY set
# * Immediate connect fail for ::1: Address not available
# *   Trying ::1...
# * TCP_NODELAY set
# * Immediate connect fail for ::1: Address not available
# * Failed to connect to localhost port 9990: Connection refused
# * Closing connection 0
# LISTENER 9991: * Rebuilt URL to: localhost:9991/
# *   Trying 127.0.0.1...
# * TCP_NODELAY set
# * connect to 127.0.0.1 port 9991 failed: Connection refused
# *   Trying ::1...
# * TCP_NODELAY set
# * Immediate connect fail for ::1: Address not available
# *   Trying ::1...
# * TCP_NODELAY set
# * Immediate connect fail for ::1: Address not available
# * Failed to connect to localhost port 9991: Connection refused
# * Closing connection 0
# LISTENER 9992: * Rebuilt URL to: localhost:9992/
# *   Trying 127.0.0.1...
# * TCP_NODELAY set
# * connect to 127.0.0.1 port 9992 failed: Connection refused
# *   Trying ::1...
# * TCP_NODELAY set
# * Immediate connect fail for ::1: Address not available
# *   Trying ::1...
# * TCP_NODELAY set
# * Immediate connect fail for ::1: Address not available
# * Failed to connect to localhost port 9992: Connection refused
# * Closing connection 0
# LISTENER 9993: * Rebuilt URL to: localhost:9993/
# *   Trying 127.0.0.1...
# * TCP_NODELAY set
# * connect to 127.0.0.1 port 9993 failed: Connection refused
# *   Trying ::1...
# * TCP_NODELAY set
# * Immediate connect fail for ::1: Address not available
# *   Trying ::1...
# * TCP_NODELAY set
# * Immediate connect fail for ::1: Address not available
# * Failed to connect to localhost port 9993: Connection refused
# * Closing connection 0
⨯ FAIL
ERR: command exited with status 1
     command:   return $res
     line:      299
     function:  run_tests
     called at: ./run-tests.sh:617
    main_test.go:35: command failed: exit status 1
```

</details>


<details>
<summary>Consul Agent Logs</summary>

```
==> Starting Consul agent...
           Version: '1.10.0-dev'
           Node ID: '46c1a80b-01e4-4ee3-aef0-31143768e942'
         Node name: 'consul-primary'
        Datacenter: 'primary' (Segment: '<all>')
            Server: true (Bootstrap: false)
       Client Addr: [0.0.0.0] (HTTP: 8500, HTTPS: -1, gRPC: 8502, DNS: 8600)
      Cluster Addr: 127.0.0.1 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false, Auto-Encrypt-TLS: false

==> Log data will now stream in as it occurs:

    2021-02-24T12:34:13.703Z [INFO]  agent.server.raft: initial configuration: index=1 servers="[{Suffrage:Voter ID:46c1a80b-01e4-4ee3-aef0-31143768e942 Address:127.0.0.1:8300}]"
    2021-02-24T12:34:13.704Z [INFO]  agent.server.serf.wan: serf: EventMemberJoin: consul-primary.primary 127.0.0.1
    2021-02-24T12:34:13.704Z [INFO]  agent.server.serf.lan: serf: EventMemberJoin: consul-primary 127.0.0.1
    2021-02-24T12:34:13.704Z [INFO]  agent.router: Initializing LAN area manager
    2021-02-24T12:34:13.705Z [INFO]  agent: Started DNS server: address=0.0.0.0:8600 network=udp
    2021-02-24T12:34:13.706Z [INFO]  agent.server.raft: entering follower state: follower="Node at 127.0.0.1:8300 [Follower]" leader=
    2021-02-24T12:34:13.707Z [INFO]  agent.server: Adding LAN server: server="consul-primary (Addr: tcp/127.0.0.1:8300) (DC: primary)"
    2021-02-24T12:34:13.707Z [INFO]  agent.server: Handled event for server in area: event=member-join server=consul-primary.primary area=wan
    2021-02-24T12:34:13.708Z [INFO]  agent: Started DNS server: address=0.0.0.0:8600 network=tcp
    2021-02-24T12:34:13.709Z [INFO]  agent: Starting server: address=[::]:8500 network=tcp protocol=http
    2021-02-24T12:34:13.709Z [WARN]  agent: DEPRECATED Backwards compatibility with pre-1.9 metrics enabled. These metrics will be removed in a future version of Consul. Set `telemetry { disable_compat_1.9 = true }` to disable them.
    2021-02-24T12:34:13.710Z [INFO]  agent: started state syncer
==> Consul agent running!
    2021-02-24T12:34:13.711Z [INFO]  agent: Started gRPC server: address=[::]:8502 network=tcp
    2021-02-24T12:34:13.771Z [WARN]  agent.server.raft: heartbeat timeout reached, starting election: last-leader=
    2021-02-24T12:34:13.771Z [INFO]  agent.server.raft: entering candidate state: node="Node at 127.0.0.1:8300 [Candidate]" term=2
    2021-02-24T12:34:13.771Z [DEBUG] agent.server.raft: votes: needed=1
    2021-02-24T12:34:13.771Z [DEBUG] agent.server.raft: vote granted: from=46c1a80b-01e4-4ee3-aef0-31143768e942 term=2 tally=1
    2021-02-24T12:34:13.771Z [INFO]  agent.server.raft: election won: tally=1
    2021-02-24T12:34:13.771Z [INFO]  agent.server.raft: entering leader state: leader="Node at 127.0.0.1:8300 [Leader]"
    2021-02-24T12:34:13.771Z [INFO]  agent.server: cluster leadership acquired
    2021-02-24T12:34:13.772Z [INFO]  agent.server: New leader elected: payload=consul-primary
    2021-02-24T12:34:13.773Z [DEBUG] agent.server: Cannot upgrade to new ACLs: leaderMode=0 mode=0 found=true leader=127.0.0.1:8300
    2021-02-24T12:34:13.778Z [INFO]  agent.leader: started routine: routine="federation state anti-entropy"
    2021-02-24T12:34:13.778Z [INFO]  agent.leader: started routine: routine="federation state pruning"
    2021-02-24T12:34:13.778Z [DEBUG] agent.server.autopilot: autopilot is now running
    2021-02-24T12:34 [...]

2021-04-16 06:44 UTC, onematchfox commented
Hi @freddygv, Just wondering if this PR is still on your radar? Would love to be able to configure tracing to start at the Ingress Gateway since without that we're essentially missing 2/3 hops, [LB->]IG->SP, in the mesh before our traces even begin.

2021-09-07 18:10 UTC, markan commented
Hello. Sorry this was left to linger so long. I'll try to get a look at the integration test issue this week.

2021-10-20 18:18 UTC, eculver commented
Thanks for following up @bbros-dev. I've been discussing a bit with @markan and other core team members about getting this prioritized and I'll just say that it's definitely on our radar and I will be spending some time in the next few weeks to try to get this unblocked. I know that doesn't solve anything for now, but you do have the attention of the maintainers and we're all excited to get this over the line.

My plan is to rebase the change and then write the integration tests. The challenge is that our integration tests for this code has changed a bit since this was created and is rather complex to setup. I'm eager to help though and will keep you posted.

Could I push changes to your remote? I haven't tried yet, but I think you have to have it turned on in your fork's settings. If not, I can work elsewhere but it will streamline things a bit.

2021-10-20 20:53 UTC, Gufran commented
Hi @eculver, thanks for prioritising this. This is my PR and you should be able to push to my fork. Just let me know if you cant and I'll give you the access explicitly.

2022-01-10 19:14 UTC, lkysow commented on website/content/docs/connect/config-entries/ingress-gateway.mdx
> +      yaml: false,
this key can be removed since this will also be supported in k8s

2022-01-10 19:59 UTC, eculver commented
Hey friends, sorry for the delayed response here. I originally picked this up thinking that the work was going to be primarily supporting our integration test suite, but it quickly grew in context to the nuances of how tracing behaves in Consul in the context of ingress gateways. For example, outside of this change, requests through an ingress gateway will not be traced unless the `x-client-trace-id: 1` header is set (see #6645). It's nuances like this we need to be aware of when making changes to the way tracing works with ingress gateways, and so I need to make sure we have everything straight before we can enable this support.

I'm still planning to get this PR updated to work with our recent integration test suite changes, but we will need to follow up with regards to documentation to make sure everything lines up. I hope this makes sense. Please feel free to ask if it doesn't.

2022-03-12 17:24 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/consul?pullRequest=8714)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/consul?pullRequest=8714)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**0** out of **2** committers have signed the CLA.


- [ ] eculver
- [ ] Gufran


---
**Gufran** seems not to be a GitHub user.
You need a GitHub account to be able to sign the CLA. If you already have a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/consul?pullRequest=8714).</sub>

2022-06-16 14:07 UTC, manobi commented
Is this feature still coming? that would put consul on next level at the company I work for.

2022-11-02 19:08 UTC, eculver commented
> Is this feature still coming? that would put consul on next level at the company I work for.

It is! I'm so sorry for the delay, but we should have it merged soon. I'm not sure if it will make it into the next major release, but it will at least be in Consul 1.15.

2022-11-07 19:22 UTC, manobi commented
> > Is this feature still coming? that would put consul on next level at the company I work for.
> 
> It is! I'm so sorry for the delay, but we should have it merged soon. I'm not sure if it will make it into the next major release, but it will at least be in Consul 1.15.

@eculver Thank you for all the effort.

2022-11-11 19:57 UTC, eculver commented on test/integration/connect/envoy/case-ingress-gateway-custom-tracing/verify.bats
> +@test "client sampling with 0% should send traces to zipkin/jaeger" {
@Gufran can you confirm that this is an accurate statement? I would expect that with client sampling == 0% no traces should be created. 

/cc @freddygv

2022-11-17 13:52 UTC, Gufran commented
Its been a while since I last dove into consul codebase, but I can go through the change-set this weekend if it helps

2022-11-21 18:33 UTC, eculver commented
> Its been a while since I last dove into consul codebase, but I can go through the change-set this weekend if it helps

Thanks @Gufran! The only question I had was around the expected behavior that I mentioned above which you answered. I am now just working on getting final sign off, so I think we're good! We'll update here as we go.

2022-12-15 18:00 UTC, eculver commented
Update: I think this is in a pretty good state. We will wait for feedback from @freddygv, but otherwise I think this is good to go.

2024-01-15 11:34 UTC, jrudowski commented
Hi,

I found this thread when digging for more information about options for triggering tracing on Consul's ingress gateway - or actually more specifically "api-gateway" now, since "ingress-gateway" has been deprecated.

"Api-gateway" seems to me behaving the same as "ingress-gateway" in consul - with RandomSampling set by Consul to 0 (opposite to Envoy's default, from what I've seen) - effectively disabling traces from ingress, unless requests are coming with "x-client-race-id" header set.
Unfortunately we're not currently in a good position to get the required header provided for traffic entering our Consul's "api-gateways", in environment where I use Consul Connect.

Does anyone know maybe - especially from Hashicorp/Consul developers end - if there are any plans finally to get that RandomSampling configurable somehow in Consul's configs for gateways with a dedicated option (without a need to getting some custom proxy defaults, which as a bit unwanted side-effect would affect also sidecar proxies)?
I see this PR is actually about 3 years old now and kind of stuck still in "Open" state - with last entries from around December 2022 - so wondering if it's been completely abandoned, with lack of interest in having that property configurable? 
Or are there maybe any chances after all in new versions of Consul, with "api-gateway". I guess (and hope) that I'm not the only one interested in having tracing a bit better configurable in Consul Connect after all these years.

Or is my only relatively easy option for now also building my own, customized Consul binary, with RandomSampling set to 100 to allow all traces everywhere, as we need it?


Out of curiosity - maybe someone could anyway also tell me - what was the reason behind this change in Consul Connect with Envoy as proxy - reverting those defaults from Envoy's 100% samples to Consul's 0?

Kind regards

2024-09-06 01:33 UTC, closed without merging